name: myfirstAcnions
on:
 push:
    branches:
      - main
jobs:
  myTesting:
    runs-on: ubuntu-latest
    steps: 
    - name: Print Hello 
      run: echo "Hello World from tasting"
    
  myDeploy:
   runs-on: ubuntu-latest
   steps: 
   - name: Print from my Deploy
     run: echo "Hello deploy"
   
