name: myfirstAcnions
env:
 APPLICATION_NAME  : "myFlask"
 PACKAGE_NAME      : "flask-deploy-ver-${{ github.sha }}"


on:
 push:
    branches:
      - main
jobs:
  myTesting:
    runs-on: ubuntu-latest
    steps: 
    - name: Print Hello 
      run: echo "Hello World from tasting"
     
    - name: Execute few commands 
      run: |
         echo "Print1"
         echo "Print2"
         echo "Application name: ${{ env.APPLICATION_NAME }}"
    - name: Open folder  
      run: ls -la
    - name: Git clone my repository  
      uses: actions/checkout@v1
    - name: Open folder  
      run: ls -la
      
  myDeploy:
   runs-on: ubuntu-latest
   needs: [myTesting]
   steps: 
   - name: Print from my Deploy
     run: echo "Hello deploy"
     
   - name: Execute Deploy 
     run: |
         echo "Print4"
         echo "Print6"
         echo "Print7"
         echo "Application name: ${{ env.PACKAGE_NAME }}"

   - name: test packeges if they here
     run: echo aws --version

   - name: has Package
     run: echo zip
   
